### ISSUE TITLE
Restricting key length

### ISSUE THREAD

**Issue by samuel-crypto** [pvial00/Cube#4]
As far as I understand the smaller keys (which have been identified weak by design), should not used. What about if there is a hard-coded exception/error preventing people from using keys shorter than `X` bits? That way: (1) it gets more idiot-proof (2) you don't confuse potential cryptoanalysts who test your cipher with a `0` 1-byte key.

Another solution would be to pad any key to the minimum secure length (just add `0`s until you get the full size key), this one has a caveat though, keys `1`, `10`, e.t.c. are now equivalent, but that is expected (a decreased search space) when dealing with 1-byte keys and I would not consider this a vulnerability

**Comment by pvial00** [comment]
This is a good point.  I've thought about implementing this as most other ciphers do make restrictions on key sizes and as you've pointed out it would prevent people from accidentally using insecure keys.  I'll put this into the next release to check and restrict key length.

**Comment by pvial00** [comment]
Fixed in v1.1.0
